# Generated by Django 5.0 on 2023-12-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Game_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(max_length=254)),
                ('category_image', models.ImageField(max_length=200, upload_to='category_images')),
                ('category_icon_upload', models.FileField(max_length=500, upload_to='category_icons')),
                ('category_icon_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('category_subtitle', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='store_frant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_game', to='Game_api.gamemaker')),
                ('device', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_divice', to='Game_api.device_frant')),
            ],
        ),
    ]
